# server:
#   port: 8761

# eureka:
#   client:
#     fetch-registry: false
#     register-with-eureka: false

eureka:
  client:
    register-with-eureka: false  # Eureka server does not register itself
    fetch-registry: false  # Disable fetching the registry from other Eureka servers (for standalone setup)
  server:
    enable-self-preservation: false  # Optionally disable self-preservation for quick service removal (in dev environments)
